gsh : gsh.c cat cd cp date kill ln ls mkdir pwd rm rmdir touch echo
	gcc -o gsh gsh.c

cat : cat.c
	gcc -o cat cat.c

cd : cd.c
	gcc -o cd cd.c

cp : cp.c
	gcc -o cp cp.c

date : date.c
	gcc -o date date.c

kill : kill.c
	gcc -o kill kill.c

ln : ln.c
	gcc -o ln ln.c

ls : ls.c
	gcc -o ls ls.c

mkdir : mkdir.c
	gcc -o mkdir mkdir.c

pwd : pwd.c
	gcc -o pwd pwd.c

rm : rm.c
	gcc -o rm rm.c

rmdir : rmdir.c
	gcc -o rmdir rmdir.c

touch : touch.c
	gcc -o touch touch.c



